apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-preview" .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - port: {{ .Values.apiGateway.servicePort }}
      targetPort: {{ .Values.apiGateway.serviceTargetPort }}
  type: {{ .Values.apiGateway.serviceType }}
{{- end }}
