apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dev
  # labels:
  #   app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1001
      containers:
        - name: api-gateway
          image: thanusri22/api-gateway:v1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_URL
            - name: TASK_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASK_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NOTIFICATION_SERVICE_URL
            - name: ANALYTICS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ANALYTICS_SERVICE_URL
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ALLOWED_ORIGINS
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10

